### ISSUE TITLE
Inappropriate PARAM types

### ISSUE THREAD

**Issue by mudrd8mz** [cwarwicker/moodle-local_utils#1]
* script should better be something like `PARAM_LOCALURL`
* link should better be `PARAM_URL`
* colour number something like `PARAM_ALPHANUM` maybe?

**Comment by cwarwicker** [comment]
Changing the param types would mean that invalid data is stripped out, leading to confusing errors or no errors at all.
For example, if the url uses PARAM_URL and they enter an invalid url, it will get stripped to `''`. It is then difficult to distinguish if that is empty because it was stripped (and an error should be displayed about it being invalid), or because they chose not to include a url (in which case it should be ignored).

It is easier to set them all to PARAM_TEXT and simply make these checks in the validation method.
